#!/usr/bin/env bash
# open-prs.sh — org-level open-PR digest for bounded-systems, written to OPEN-PRS.md.
#
# The "what's waiting to merge across every repo" view. Complements audit.mjs
# (repo governance) and fleet (live CI): this is the merge queue. Regenerate with
#   bash scripts/open-prs.sh
# The scheduled .github/workflows/open-prs.yml also renders it to the Actions summary.
#
# Requires: gh (authed; org read scope for private repos), jq.
set -euo pipefail
ORG="${ORG:-bounded-systems}"
OUT="${1:-OPEN-PRS.md}"

json=$(gh search prs --owner "$ORG" --state open --limit 300 \
  --json repository,number,title,author,isDraft,createdAt)

total=$(echo "$json" | jq 'length')
bots=$(echo "$json" | jq '[.[] | select(.author.login | endswith("[bot]"))] | length')
drafts=$(echo "$json" | jq '[.[] | select(.isDraft)] | length')

{
  echo "# Open PRs — $ORG"
  echo
  echo "_Generated by \`scripts/open-prs.sh\` — the org-level merge queue: what's waiting, and what automation is stuck. Do not edit by hand._"
  echo
  echo "**$total open** · 🤖 $bots bot · ✏️ $drafts draft"
  echo
  echo "> ⚠️ **Bot PRs are blocked by the org \`required_signatures\` ruleset** unless the bot"
  echo "> signs its commits or is a \`bypass_actor\`. A rising bot count means automation"
  echo "> (incl. Dependabot **security** updates) is piling up unmerged — check the ruleset bypass list."
  echo
  echo "Live: <https://github.com/pulls?q=is:open+is:pr+org:$ORG>"
  echo
  echo "| Repo | PR | | Author | Title |"
  echo "|------|----|--|--------|-------|"
  echo "$json" | jq -r '
    sort_by(.repository.name, .number)[] |
    "| \(.repository.name) | [#\(.number)](https://github.com/'"$ORG"'/\(.repository.name)/pull/\(.number)) | \(if (.author.login | endswith("[bot]")) then "🤖" elif .isDraft then "✏️" else "" end) | \(.author.login) | \(.title | gsub("\\|"; "\\|")) |"'
} > "$OUT"

echo "wrote $OUT — $total open PRs ($bots bot, $drafts draft)"
